### ISSUE TITLE
st changes size depending on font size

### ISSUE THREAD

**Issue by AlexBocken** [LukeSmithxyz/st#279] opened 2021-02-23 10:42 UTC
I've noticed since the most recent 0.8.4 that st seems to be all over the place with its window size.

It now seems to enforce the `borderpx` value instead of trying to adhere to the given dimension by the window manager. In previous builds st just padded the terminal window to get to the wanted size given by the window manager. 

This looks rather wonky in tiling window managers with a larger font size in st.

The reason for this is probably somewhere in `x.c` but on a first glance I haven't found anything easy to fix this. Maybe someone else has also come across this behaviour and also wants it fixed. Would love to here insights from others how to remove this behaviour.

**Comment by AlexBocken** [comment] 2021-02-23 10:49
Here's a picture of the issue. That might explain this issue a bit better:

<img src=https://bocken.org/st_0.8.4_font_size_issues.png>

**Comment by LukeSmithxyz** [comment] 2021-02-23 13:29
Duplicate of https://github.com/LukeSmithxyz/st/issues/275

**Closed by LukeSmithxyz** 2021-02-23 13:29 UTC

**Comment by AlexBocken** [comment] 2021-02-23 13:31
Ah, didn't see that one. Seems like my search parameters were a bit off. Thanks!
