### ISSUE TITLE
Broken after upgrading

### ISSUE THREAD

**Issue by AJCM-git** [LukeSmithxyz/st#172] opened 2020-03-23 23:52 UTC
I installed this with larbs, today i did a pretty big upgrade with `pacman -Syyu` and now my terminal looks like pic related.
I also noticed that `pacman -Q` doesnt list st
![image](https://user-images.githubusercontent.com/60196617/77373888-c3965d00-6d3f-11ea-950f-dace50edee00.png)

**Comment by LukeSmithxyz** [comment] 2020-03-24 00:03
Duplicate of https://github.com/LukeSmithxyz/LARBS/issues/186

pacman does not list st because it is manually installed.

**Closed by LukeSmithxyz** 2020-03-24 00:03 UTC
