### ISSUE TITLE
follow urls error on latest build

### ISSUE THREAD

**Issue by m160** [LukeSmithxyz/st#193] opened 2020-04-16 17:30 UTC
I was using one of your old builds of st so I decided to install the latest one today and now alt+l/y doesn't work anymore. It looks like it's trying to display the urls like before, but inside the st window, it basically just shows as a quick flicker. Not sure what has changed. I'm not using LARBS, I'm on Pop!_OS 19.10.

This is the error I'm getting:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  84
  Current serial number in output stream:  85
```

**Comment by LordRusk** [comment] 2020-04-16 17:35
I was having this problem too. Whether its my personal dmenu build or a fresh one, doesn't work. When I installed luke's build of dmenu though, for some reason, it works.

**Comment by LukeSmithxyz** [comment] 2020-04-16 18:49
Oh I think I know what this is. For a while on my own build I've had st use an embedded dmenu to open urls (never pushed the change here). The problem is if you don't have a build of dmenu that can handle transparency like mine, it won't work.

In this last commit, I inadvertently switched it to embed when I was changing the same lines. I've fixed it so it will no longer try to embed dmenu. Just pull and reinstall and it should be fixed.

**Closed by LukeSmithxyz** 2020-04-16 18:49 UTC

**Comment by LukeSmithxyz** [comment] 2020-04-16 18:51
If you do want to be able to embed dmenu on partttially transparent windows, just check out my dmenu build: https://github.com/lukesmithxyz/dmenu, specifically d1a3c6cd1f8c84109ac181c8a7dbb29181862aea.

**Comment by m160** [comment] 2020-04-16 22:47
I kinda forgot that your build of st has transparency as I don't have a compositor installed. Added the alpha patch in case I get to that one day and that fixed it, thanks!
