### ISSUE TITLE
ST+DMENU wide character spacing FYI

### ISSUE THREAD

**Issue by MrDarthShoe** [LukeSmithxyz/st#171] opened 2020-03-23 16:29 UTC
With new ttf-inconsolata 1:3.000-1, there is problem with wide character spacing.
The same applies to dmenu.

Here is official issue to ttf-inconsolata guys to have in mind:
https://bugs.archlinux.org/task/65932?project=5&string=ttf-inconsolata

Changing from Inconsolata to i.e. "Liberation Mono" solves issue, but it looks badly.

**Comment by LukeSmithxyz** [comment] 2020-03-23 16:32
Duplicate of https://github.com/LukeSmithxyz/LARBS/issues/186

This is an upstream issue.

**Closed by LukeSmithxyz** 2020-03-23 16:32 UTC
