### ISSUE TITLE
/ in prompt causing awk to fail

### ISSUE THREAD

**Issue by ryant18** [LukeSmithxyz/st#157] opened 2020-01-30 14:11 UTC
I'm using Ubuntu 18.04

I've modified st-copyout to print $chosen and $eps1

    ...
    eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
    echo "chosen:"
    echo $chosen
    echo "eps1:"
    echo $eps1
    awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard

Output:

    chosen:
    [r][y][a][n][@][h][u][a][w][e][i][:][~][/][p][r][o][j][e][c][t][s][/][s][t][$][ ][l][s][ ] 
    eps1:
    [r][y][a][n][@][h][u][a][w][e][i][:][~][/][p][r][o][j][e][c][t][s][/][s][t][$]

So it is successfully picking up my selection, however awk gives an error when trying to process it

    awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
    ^[r][y][a][n][@][h][u][a][w][e][i][:][~][
    awk: line 1: syntax error at or near ]
    awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
    [r][y][a][n][@][h][u][a][w][e][i][:][~][
    awk: line 1: syntax error at or near ]

It looks like the `/` in `ryan@huawei:~/projects` is getting matched as the closing `/` in  
`awk "/^$chosen$/...`

If I try to copy a command in my home directory, so the prompt is `ryan@huawei:~$` then st-copyout  successfully copies as there is no `/` in the prompt.

I'm really confused as to how I can get awk to process a prompt with a `/` in it.

**Comment by LukeSmithxyz** [comment] 2020-04-28 23:55
I haven't ever been able to replicate this problem, even when I put a slash in my PS1. Could you provide your exact prompt setup so I can test it?

**Comment by sawyer07** [comment] 2020-09-07 06:47
Can you replicate the problem in #165 which was closed as a duplicate of this one? (NB back slash vs forward slash) Thanks

**Closed** 2020-10-13 00:54 UTC
