### ISSUE TITLE
child exited with status 1

### ISSUE THREAD

**Issue by cmF3** [LukeSmithxyz/st#274] opened 2021-02-06 10:51 UTC
Latest update including the update to 0.8.4 makes st crash on start for me with 'child exited with status 1'.

I have reverted to 73c034ba05101e2fc337183af1cdec5bfe318b99,

**Comment by LukeSmithxyz** [comment] 2021-02-06 13:16
Do you have `git` installed? I can't think of what else would cause the issue.

Are you using an AUR helper or manually compiling or what?

**Comment by LukeSmithxyz** [comment] 2021-02-06 14:15
The AUR build is bulidng fine with the new version as well for me.

**Comment by BachoSeven** [comment] 2021-02-06 17:49
The update runs fine, I even merged it on top of my build(which has very few additional patches).

However, I have another issue: some terminals with `neovim` open in them "freeze", and I have to close them with Super+q. I don't think it's the additional patches, so it's either some `nvim` plugin I have (although it's unlikely imo that it would conflict with the `st` update), or it's an issue for others as well?
It does not seem to happen with terminals without `nvim` in them.

**Comment by LukeSmithxyz** [comment] 2021-02-06 17:50
I think I've run into that issue once or twice in testing. Not sure what the issue is because it hasn't happened too much to test. Probably something with `scroll` though.

**Comment by cmF3** [comment] 2021-02-06 21:12
> Are you using an AUR helper or manually compiling or what?

I am manually compiling the source in ~/.local/src/st, provided by the LARBS install.

**Comment by LukeSmithxyz** [comment] 2021-02-06 21:17
What are the contents of the `scroll/` directory inside?

You might want to run `git submodule init` and `git submodule update` manually and see if that adds the repo if not their already.

**Comment by cmF3** [comment] 2021-02-06 21:25
I found the issue. The problem is running 'sudo make install' in the st directory, which installs scroll to /usr/local/bin with permissions 700, id:gid 0:0. This obviously won't execute as user and st silently fails.

I think it would be better to use install(1) with an appropriate permission mode, something like 755 in scroll/Makefile line 14-15.

**Closed** 2021-02-06 22:21 UTC

**Comment by LukeSmithxyz** [comment] 2021-02-06 22:22
I think that should do it.

I might just merge these two repositories in the future because I don't see `scroll` being used aside from st. We'll see.
