### ISSUE TITLE
Icon cropping

### ISSUE THREAD

**Issue by dumbPy** [LukeSmithxyz/st#67] opened 2019-05-06 08:06 UTC
icons from lsd are cropped in my st fork. Does it work for you properly? I am on ubuntu-gnome and the same thing happens in gnome-terminal. 

![Screenshot from 2019-05-06 13-33-05](https://user-images.githubusercontent.com/34011516/57213170-9ba4ea80-7003-11e9-9923-d7be02425ac7.png)

Lowest icon is how all icons are cropped in lsd. Upper icon shows how it looks after hitting return.

**Comment by jonbulica99** [comment] 2019-06-03 22:21
I can reproduce the issue, it's also present on upstream. Oddly enough it only happens when your cursor/prompt is after the character. If you move it before the char and refresh the terminal (e.g. by zooming in/out) it will be rendered correctly.

**Comment by LukeSmithxyz** [comment] 2020-02-08 03:46
I'm going to close this issue because I've added a work around regardless of the origin of this issue. You can manually set your fallback fonts, specifically your emoji fonts at a lower size that will avoid all this problem. I have the default font size at 14pt now, with JoyPixel emojis at only 10pt. If you use emojis other than JoyPixels, you can change the relevant line in the config file yourself.

**Closed by LukeSmithxyz** 2020-02-08 03:46 UTC

**Comment by Mattio-cmd** [comment] 2022-04-19 00:53
> I'm going to close this issue because I've added a work around regardless of the origin of this issue. You can manually set your fallback fonts, specifically your emoji fonts at a lower size that will avoid all this problem. I have the default font size at 14pt now, with JoyPixel emojis at only 10pt. If you use emojis other than JoyPixels, you can change the relevant line in the config file yourself.

Not true, im using JoyPixel in 9 and still some icons are cropped
