### ISSUE TITLE
transparency breaks ranger image display feature

### ISSUE THREAD

**Issue by toufikbelouadah** [LukeSmithxyz/st#6] opened 2018-08-05 16:47 UTC
when i set in config.h : 
unsigned int alpha  = 0xff;  which mean no transparency everything works fine.
when i set the transparency to 0xed for example ranger cant display images
anyone can help or experienced the same issue ?
https://imgur.com/a/JGanPCq

**Comment by gh00sty** [comment] 2018-08-05 20:25
iam using compton with default settings.
in the past i was using rxvt-unicode and it worked fine with transparency but its bloated 
and i like the way st treats configs from source, so i guess i will sacrifice transparency until i find a way to fix it 
if u have any idea please let me know otherwise you close this since its not a bug in "st" like i thought 
thank you Luke ^^

**Comment by LukeSmithxyz** [comment] 2018-08-05 20:32
Hmm. Well since we are using the same builds, I can't be sure of the difference to make it fail on your machine and work on mine.

If you want to see my compton config it's [here](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/compton.conf), although I just tried it without the config and the image previews still worked on my computer.

Just to be sure, in case you just reinstalled your system, you do have `w3m`, etc. installed right?

**Comment by toufikbelouadah** [comment] 2018-08-05 21:26
yes w3m is installed and set as image preview handler in ~/.config/ranger/rc.conf
and here is the list of installed all installed packages you can " Ctrl + F " a specific package you might think it might be the cause https://ghostbin.com/paste/ama7h/raw

the only difference we might have is the wm i use bspwm and you use i3 but i don't think that's the cause anyway i will give i3 a run and see if the problem still persist.

**Closed** 2018-08-09 20:37 UTC
